// app/api/scenario/start/route.ts
//
// Starts a scenario. Returns the patron's opening line + Polly audio.
//
// Owner: Role A (scenario simulator).
// TODO: replace the canned opening line with one generated by Bedrock that
// varies the patron's mood between runs (so demo replay feels different).

import { NextRequest, NextResponse } from "next/server";
import { synthesize } from "@/lib/polly";
import { SCENARIO_OPENERS } from "@/lib/prompts";
import { generateText } from "@/lib/bedrock";
import { PATRON_ROLEPLAY } from "@/lib/prompts";

const PATRON_VOICE = process.env.POLLY_PATRON_VOICE_ID ?? "Matthew";

const PATRON_OPENING_LINES: Record<string, string> = {
  trespass: "Look, I'm not bothering anyone. I paid for my drink. Why do I have to leave?",
  intoxicated: "I'm fine, man. I had like, two drinks. I'm just gonna drive home.",
  use_of_force: "Hey — back off. I didn't do anything. He started it.",
  fire_alarm: "Is this real? Or is this a drill? My friends are still inside.",
  evidence: "What? I didn't take anything. You can't search me.",
  medical: "(unconscious — no response)",
};

export async function POST(req: NextRequest) {
  const { scenarioId } = (await req.json()) as { scenarioId: string };

  const sceneSetup = SCENARIO_OPENERS[scenarioId];
  if (!sceneSetup) {
    return NextResponse.json({ error: "Unknown scenario" }, { status: 400 });
  }

  // Use the canned opening for speed/consistency. The mid-scenario turns
  // are where Bedrock truly drives the roleplay.
  let patronLine = PATRON_OPENING_LINES[scenarioId] ?? "Hey, what do you want?";

  // If you'd like more variation in the future, uncomment:
  // patronLine = await generateText(
  //   [{ role: "user", content: `Scenario setup: ${sceneSetup}\n\nGive your opening line as the patron.` }],
  //   PATRON_ROLEPLAY,
  //   { maxTokens: 80, temperature: 0.8 }
  // );

  const audio = await synthesize(patronLine, PATRON_VOICE);

  return NextResponse.json({
    patronLine,
    sceneSetup,
    audioBase64: audio.audioBase64,
  });
}
